### PR TITLE
Use a method compatible with mongoid-observers to determinine the version of mongoid (without versionomy dependency)

### PR DESCRIPTION
**Pull request by reedlaw**
Same as dblock's PR but without the added dependency.

### CODE REVIEW

**Comment by reedlaw** [comment]
This is a fix for PR #126

**Comment by johnnyshields** [comment]
+1 :+1:

**Comment by dblock** [comment]
I am fine merging this, can you rebase/squash it please?

**Comment by reedlaw** [comment]
OK, I had to do a force push so hopefully no one used my branch yet.

**Comment by dblock** [comment]
Merged via https://github.com/aq1018/mongoid-history/commit/83038845beabb91b9af22bc20ff1e6dda5cfe5e8.

**Comment by dblock** [comment]
Would really appreciate this going into a bunch of other gems, you could start with a list at http://code.dblock.org/2011/05/27/ror-win-getting-things-done-with-mongodb-mongoid.html.

**Comment by dblock** [comment]
I released 0.4.5.

**Pull request closed without merging**
