### PR TITLE
Use a method compatible with mongoid-observers to determinine the version of mongoid.

### LINKED ISSUE #121: undefined local variable or method `metadata', incompatible with mongoid-observers
Hi,
I got <a href='https://gist.github.com/zeitnot/31c507f0a6a4714a9d11'>this</a> error. I do not know why. What is the proper way to install this gem.

### PR DESCRIPTION
**Pull request by dblock**
Fixes #121, see #123.

### CODE REVIEW

**Comment by zeitnot** [comment]
ping @dblock

**Comment by dblock** [comment]
Merged https://github.com/aq1018/mongoid-history/commit/83038845beabb91b9af22bc20ff1e6dda5cfe5e8.

**Comment by zeitnot** [comment]
@dblock appreciated :)

**Comment by dblock** [comment]
I released 0.4.5.

**Pull request closed without merging**
