### PR TITLE
Fix RequestStore specs

### PR DESCRIPTION
**Pull request by johnnyshields**
This PR is purely a fix to specs related to my last PR. No logic change.

### CODE REVIEW

**Comment by dblock** [comment]
Hmmm... that seems backwards. We don't want to require the thing we don't have or to auto-require it every time.

**Comment by johnnyshields** [comment]
This is just as a development dependency for testing. It won't be used when running the gem in an app.

**Comment by johnnyshields** [comment]
And also, the recommendation should be to use RequestStore wherever possible, esp. when using a threaded server like Puma.

**Comment by dblock** [comment]
@johnnyshields I think we need a set of tests to run without loading `request_store`, otherwise we'll never catch bugs when `request_store` is not installed. That's why there's that `if` in the Gemfile. I think if we want `request_store` all the time, we should just make it a real dependency and call it a day. I'd be OK with it.

**Comment by johnnyshields** [comment]
@dblock I don't think we need to double our travis runs for just testing RequestStore. I will change the PR so RequestStore is hidden by default in the specs, and we turn it on just for request-store specific specs.

**Comment by johnnyshields** [comment]
@dblock I've implemented a new approach here.

**Comment by dblock** [comment]
@johnnyshields I think we disagree on what's going on here. RequestStore is a feature that gets automatically turned on when present via https://github.com/aq1018/mongoid-history/blob/752c70b3ed6c329ed00c5a42c9b442f3b131a0f9/lib/mongoid/history.rb#L30. So we _must_ test both AFAIK unless we remove that code and just default to RequestStore vs. Thread, but I don't know why we should. You're actively removing tests that test both scenarios, and I think that's a bad thing. Travis time is really of very little concern, no? Thoughts?

**Comment by johnnyshields** [comment]
I don't think it's wise to double our Travis run time every time we add something like this.

RequestStore is billed as a drop-in replacement for Thread.current. It is only used as storage for the global enable/disable flag, which is not related to the "guts" of the gem logic. I believe the tests as I have them in this PR are adequate to test the functionality.

**Comment by dblock** [comment]
I'll merge, but I will politely disagree. No strong feelings though.

**Comment by dblock** [comment]
Re: doubling Travis time I would take the approach of declaring the matrix as in https://github.com/ruby-grape/grape-swagger/blob/master/.travis.yml for example.

**Pull request merged**
